In [1]:
import numpy as np 

In [3]:
a = np.arange(15).reshape(3,5) 

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape

(3, 5)

In [6]:
a.ndim

2

In [7]:
a.dtype.name 

'int64'

In [8]:
a.itemsize

8

In [9]:
a.size

15

In [11]:
b = np.array([1,2,3])

In [12]:
b

array([1, 2, 3])

In [16]:
b.dtype

dtype('int64')

In [17]:
type(b)

numpy.ndarray

In [18]:
b = np.array([1.2,4.5,3.5])

In [19]:
b.dtype

dtype('float64')

In [23]:
b = np.array(([(1.5,2,3),(4,5,6)]))

In [24]:
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [27]:
a = np.array([1,2,3])

In [28]:
a+b

array([[ 2.5,  4. ,  6. ],
       [ 5. ,  7. ,  9. ]])

In [29]:
b>10

array([[False, False, False],
       [False, False, False]], dtype=bool)

In [31]:
np.empty([2,3])

array([[ 2.5,  4. ,  6. ],
       [ 5. ,  7. ,  9. ]])

In [32]:
c = np.arange(9).reshape(3,3) 

In [33]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
c.itemsize * c.size

72

In [38]:
d = np.random.random(30)

In [41]:
print(d)
print(d.mean())

[ 0.42217808  0.38936606  0.58570787  0.23950687  0.71172636  0.66028781
  0.26040845  0.04777169  0.18087943  0.00968974  0.6540683   0.23951167
  0.2415455   0.63019831  0.28470131  0.83602971  0.85820282  0.19428217
  0.05072981  0.18951659  0.50324619  0.72658379  0.65830677  0.44813409
  0.69707934  0.9286748   0.70522807  0.60020602  0.47358876  0.226945  ]
0.455143380018
